# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-04 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190504_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeitem',
            name='user',
        ),
    ]
