# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-04 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0003_remove_resumeitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
